### ISSUE TITLE
Set up dictionary-writer testing in Jenkins

### ISSUE THREAD

**Issue by jakebeal** [SD2E/sbol-dictionary-writer#1]
(migrated and adapted from old GitLab repository)

The dictionary-writer has tests, but they aren't running on TACC Jenkins CI yet.

**Comment by eriksf** [comment]
sbol-dictionary-writer Jenkins job has been set up at http://jenkins.sd2e.org. As with the dictionary-maintainer job, the token (token.pickle) had to be copied over to the job workspace on the Jenkins server. The same users will be notified of job/test failures.
